#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apisixconsumers.apisix.apache.org
spec:
  group: apisix.apache.org
  scope: Namespaced
  names:
    plural: apisixconsumers
    singular: apisixconsumer
    kind: ApisixConsumer
    shortNames:
      - ac
  preserveUnknownFields: false
  versions:
    - name: v2beta3
      served: true
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - authParameter
              properties:
                authParameter:
                  type: object
                  oneOf:
                    - required: ["basicAuth"]
                    - required: ["keyAuth"]
                    - required: ["wolfRBAC"]
                    - required: ["jwtAuth"]
                    - required: ["hmacAuth"]
                    - required: ["openidConnect"]
                  properties:
                    basicAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            username:
                              type: string
                              minLength: 1
                            password:
                              type: string
                              minLength: 1
                          required:
                            - username
                            - password
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    keyAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            key:
                              type: string
                              minLength: 1
                          required:
                            - key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    jwtAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            key:
                              type: string
                              minLength: 1
                            secret:
                              type: string
                            public_key:
                              type: string
                            private_key:
                              type: string
                            algorithm:
                              type: string
                            exp:
                              type: integer
                            base64_secret:
                              type: boolean
                          required:
                            - key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    wolfRBAC:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            server:
                              type: string
                            appid:
                              type: string
                            header_prefix:
                              type: string
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    hmacAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            access_key:
                              type: string
                            secret_key:
                              type: string
                            algorithm:
                              type: string
                            clock_skew:
                              type: integer
                            signed_headers:
                              type: array
                              items:
                                type: string
                            keep_headers:
                              type: boolean
                            encode_uri_params:
                              type: boolean
                            validate_request_body:
                              type: boolean
                            max_req_body:
                              type: integer
                          required:
                            - access_key
                            - secret_key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
    - name: v2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - authParameter
              properties:
                authParameter:
                  type: object
                  oneOf:
                    - required: ["basicAuth"]
                    - required: ["keyAuth"]
                    - required: ["wolfRBAC"]
                    - required: ["jwtAuth"]
                    - required: ["hmacAuth"]
                    - required: ["openidConnect"]
                  properties:
                    basicAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            username:
                              type: string
                              minLength: 1
                            password:
                              type: string
                              minLength: 1
                          required:
                            - username
                            - password
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    keyAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            key:
                              type: string
                              minLength: 1
                          required:
                            - key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    jwtAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            key:
                              type: string
                              minLength: 1
                            secret:
                              type: string
                            public_key:
                              type: string
                            private_key:
                              type: string
                            algorithm:
                              type: string
                            exp:
                              type: integer
                            base64_secret:
                              type: boolean
                          required:
                            - key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    wolfRBAC:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            server:
                              type: string
                            appid:
                              type: string
                            header_prefix:
                              type: string
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    hmacAuth:
                      type: object
                      oneOf:
                        - required: ["value"]
                        - required: ["secretRef"]
                      properties:
                        value:
                          type: object
                          properties:
                            access_key:
                              type: string
                            secret_key:
                              type: string
                            algorithm:
                              type: string
                            clock_skew:
                              type: integer
                            signed_headers:
                              type: array
                              items:
                                type: string
                            keep_headers:
                              type: boolean
                            encode_uri_params:
                              type: boolean
                            validate_request_body:
                              type: boolean
                            max_req_body:
                              type: integer
                          required:
                            - access_key
                            - secret_key
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                    openidConnect:
                      type: object
                      oneOf:
                        - required: [ "value" ]
                        - required: [ "secretRef" ]
                      properties:
                        value:
                          type: object
                          properties:
                            client_id:
                              type: string
                            client_secret:
                              type: string
                            discovery:
                              type: string
                            scope:
                              type: string
                            realm:
                              type: string
                            bearer_only:
                              type: boolean
                            logout_path:
                              type: string
                            post_logout_redirect_uri:
                              type: string
                            redirect_uri:
                              type: string
                            timeout:
                              type: integer
                            ssl_verify:
                              type: boolean
                            introspection_endpoint:
                              type: string
                            introspection_endpoint_auth_method:
                              type: string
                            token_endpoint_auth_method:
                              type: string
                            public_key:
                              type: string
                            use_jwks:
                              type: boolean
                            use_pkce:
                              type: boolean
                            token_signing_alg_values_expected:
                              type: string
                            set_access_token_header:
                              type: boolean
                            access_token_in_authorization_header:
                              type: boolean
                            set_id_token_header:
                              type: boolean
                            set_userinfo_header:
                              type: boolean
                            set_refresh_token_header:
                              type: boolean
                            session:
                              type: object
                              properties:
                                secret:
                                  type: string
                          required:
                            - client_id
                            - client_secret
                            - discovery
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name